### ISSUE TITLE
Git Repository Linkup with Source Files

### ISSUE THREAD

**Issue by laylar** [laylar/wag#1]
We have discovered that will need to make the meta file visible (done) and that we may need to use .gitignore to adjust the way Git Hub uses the library files: http://answers.unity3d.com/questions/369755/unity-on-github.html

**Comment by JoeMonger** [comment]
Try the new pull.  Think I mighta cracked this one!

**Comment by laylar** [comment]
The clone has some of the data (the code), but not all (the gui objects). I suspect there's more to do.

**Comment by laylar** [comment]
Yay! It was an issue of File -> Open Scene -> Words. That opened up the one and only scene that we have so far created.
